package Nov.ex_18_nov_Exception;

public class lab178_try_catch {
    public static void main(String[] args) {
        int a=10;
        int c= a/0;
        System.out.println(c);

    }
}
